# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# push:
#   branches: 
#   - master 

name: 步步宝

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 0-23 * * *'
  watch:
     types: started
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【书旗小说】'
        run: |
          node Task/shuqi.js
        env:
          shuqiuserurlVal: ${{ secrets.shuqiuserurlVal }}
          shuqisyurlVal: ${{ secrets.shuqisyurlVal }}
          shuqisybodyVal: ${{ secrets.shuqisybodyVal }}
          shuqispbodyVal: ${{ secrets.shuqispbodyVal }}
          shuqiscbodyVal: ${{ secrets.shuqiscbodyVal }}
          shuqiydbodyVal: ${{ secrets.shuqiydbodyVal }}
          shuqiqdbodyVal: ${{ secrets.shuqiqdbodyVal }}		
          shuqirwbodyVal: ${{ secrets.shuqirwbodyVal }}
          shuqifxbodyVal: ${{ secrets.shuqifxbodyVal }}
          shuqisprwurlVal: ${{ secrets.shuqisprwurlVal }}
          shuqijlbodyVal: ${{ secrets.shuqijlbodyVal }}
          shuqicjyurlVal: ${{ secrets.shuqicjyurlVal }}
          shuqicjcsbodyVal: ${{ secrets.shuqicjcsbodyVal }}
          shuqicjbodyVal: ${{ secrets.shuqicjbodyVal }}
          shuqijsspbodyVal: ${{ secrets.shuqijsspbodyVal }}
          shuqijsydurlVal: ${{ secrets.shuqijsydurlVal }}
          shuqijsydbodyVal: ${{ secrets.shuqijsydbodyVal }}
          shuqijsqdbodyVal: ${{ secrets.shuqijsqdbodyVal }}
          shuqijsqdspyurlVal: ${{ secrets.shuqijsqdspyurlVal }}
          shuqijsrwbodyVal: ${{ secrets.shuqijsrwbodyVal }}
          shuqijsfxbodyVal: ${{ secrets.shuqijsfxbodyVal }}
          shuqijssprwurlVal: ${{ secrets.shuqijssprwurlVal }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TXNEWS_NOTIFY_CONTROL: ${{ secrets.TXNEWS_NOTIFY_CONTROL }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
